### ISSUE TITLE
[공통] 카테고리 상세 태그 정의

### ISSUE THREAD

**Issue by sihyung92** [woowacourse-teams/2021-jujeol-jujeol#114]
### 설명
- [노션링크](https://www.notion.so/ca3a941b1cf9406d9a55316f12250acb)
- 상세 분류의 구분 방식을 정의한다.
- ex ) 라거, 에일, 흑맥주를 맥주의 상세 태그로 두어야 할까?
### 진행상황
- [x] 상세 분류 방식을 정한다.

**Comment by sunhpark42** [comment]
카테고리 분류 : 맥주, 소주, 와인, 막걸리, 양주, 칵테일, 기타로 분류
태그로 관리할 소 분류 : 고량주 사케 위스키 칵테일(바카디 모히또 같은 애들 따로 팜) 데낄라 보드카 럼 진 리큐르 과실주.. 등

참고 문서 : https://www.notion.so/2770295fbc284cb8aff546eccc756df7
