### ISSUE TITLE
[공통] 내가 마신 술에 대한 정책 회의

### ISSUE THREAD

**Issue by devhyun637** [woowacourse-teams/2021-jujeol-jujeol#270]
### 설명
- '내가 마신 술' 이 현재 선호도로 체크가 되도록 되어있는데, 선호도를 남기지 않고 리뷰를 남겼을 경우 '술을 마시지 않았다'라는 의미가 모호한 것 같아서 이 부분에 대한 논의가 필요합니다.
- '내가 마신 술'이라는 명칭을 '선호도를 남긴 술'이라고 하거나, 선호도를 체크해야만 리뷰를 적용할 수 있도록 로직을 변경할 필요가 있습니다.

**Comment by sunhpark42** [comment]
![](https://user-images.githubusercontent.com/67677561/128367822-7c931d26-ed68-43ac-8924-2b42f1031527.png)

**Comment by sunhpark42** [comment]
### 결정 : '내가 마신 술'로 주제를 유지하고, 선호도를 입력해야만 리뷰를 작성할 수 있도록 로직을 변경한다.

> 현재 우리팀의 추천 알고리즘을 위해서는 선호도에 대한 정보를 모으는 것이 더 중요함

정책

*   선호도 only
*   리뷰에는 선호도 무조건

작동

*   선호도가 없을 때 리뷰 작성칸에 placeholder에 선호도를 먼저 작성해 주세요 후 비활성화
*   리뷰 작성칸 근처에 '선호도 입력하기' 이런거 하나 넣고, 누르면 상단 선호도 입력 위치로 스크롤 변경

변경사항

*   '내가 마신 술' ⇒ '선호도 남긴 술' 로 변경
*   API → 선호도 없이 리뷰 남긴 건 에러로 처리 => 보류
*   UI 3안, 6안 합치기
