### ISSUE TITLE
[QA]모바일 사파리에서 API 요청 후 별 아이콘 색이 흰색으로 변경되는 이슈

### ISSUE THREAD

**Issue by sunhpark42** [woowacourse-teams/2021-jujeol-jujeol#467]
### QA 환경
- 모바일 사파리

### 현상
- 1\. 닉네임 수정 후 별 아이콘 색이 흰색으로 변경됨.
- 2\. 상세페이지에서 리뷰를 등록하면 별 아이콘 색이 흰색으로 변경됨.

### 재현 과정
- 1\.  로그인 후 마이페이지 > 닉네임 수정 > 내 주류의 별 확인.
-  2\. 리뷰 작성 후 선호도 확인.

### 예상되는 원인
- 모바일 사파리에서의 svg 이슈.

### 스크린샷:

**Comment by devhyun637** [comment]
default 색을 노란색으로 지정함으로써 해결했습니다
