### ISSUE TITLE
[QA][모바일 사파리] 리뷰 등록 버튼 글자 크기 작음.

### ISSUE THREAD

**Issue by sunhpark42** [woowacourse-teams/2021-jujeol-jujeol#477]
### QA 환경
-모바일 사파리

### 현상
- 모바일 사파리에서 리뷰 작성 완료 버튼 내 글자크기가 작은 이슈.

### 재현 과정
- 모바일 사파리에서 리뷰 작성.

### 예상되는 원인
- 버튼 크기 설정 확인 필요할 것 같음. (아이패드에서도 작게나옴.)

### 스크린샷:

**Comment by devhyun637** [comment]
해상도별 차이가 나는데, 심각한 수준으로 작은 게 아니라서 클로즈합니다.
