### ISSUE TITLE
[FE] 번들 옵션에서 소스맵 생성 비활성화

### ISSUE THREAD

**Issue by devhyun637** [woowacourse-teams/2021-jujeol-jujeol#593]
### 설명
- 현재 번들사이즈가 소스맵으로 인해서 3.2MB인데, 프로덕션 모드에서는 소스맵이 필요없다고 판단됩니다. 이에 sourceMap:false 옵션을 넣어도 될 것 같습니다.
- 소스맵을 제거한 상태에서 프로덕션 모드로 번들했을 경우 번들 사이즈
<img width="270" alt="스크린샷 2021-11-14 오후 8 47 32" src="https://user-images.githubusercontent.com/59258239/141679498-32739c75-3763-480c-9d95-2181a95cb256.png">

**Comment by sunhpark42** [comment]
동의합니다. 저도 고민하고 있었는데 이슈 올려주셔서 감사해용.

소스맵이 번들된 파일과 원본된 파일을 연결해 주는 수단이라서,

디버깅이 필요 없는 prod환경에서는 불필요하다고 생각됩니다. :)
