### ISSUE TITLE
[BE] n+1 쿼리 이슈

### ISSUE THREAD

**Issue by perenok** [woowacourse-teams/2021-jujeol-jujeol#638]
### 설명
현재 n+1 쿼리로 인해 마이크로 서버에서 버티지 못하고 있음.

### 주안점
* [ ] 문제 발생 포인트 찾기
* [ ] 해당 쿼리 최적화

**Comment by qhals321** [comment]
현재 마이크로 서버가 버티질 못하고 있습니다. 문제점을 찾아보니 각 주류에 대한 멤버가 남긴 평점을 찾아올 때 n+1 쿼리가 나가는 문제입니다.
```
recommendDrinks.stream()
                .map(drink -> DrinkDto.create(drink.getDrink(),
                        // 여기서 n+1 으로 멤버의 preference 를 찾아오게 됨
                        preferenceService.showByMemberIdAndDrink(loginMember.getId(), drink.getDrink()),
                        drink.getExpectedPreference()))
                .sorted((o1, o2) -> Double
                        .compare(o2.getExpectedPreference(), o1.getExpectedPreference()))
                .collect(Collectors.toList());
```

### 임시 방편
먼저, 서버 복구가 우선이라 생각해 각 주류에 대한 멤버가 남긴 평점을 찾는 부분을 제외했습니다. 
```
drinkRepository.findAllSortByPreference(pageable)
                .getContent()
                .stream()
                .map(drink -> DrinkDto.create(drink, Preference.anonymousPreference(drink), 0))
                .collect(Collectors.toList());
```
해당 부분은 develop 브랜치에 들어가지 않고 refactor/recommend 임시 브랜치를 이용해 서버에 배포된 상태입니다.
만일, 코드 리팩토링 혹은 문제 해결에 대한 정확한 그림이 그려진다면 refactor/recommend 브랜치는 삭제되고 새로운 브랜치를 열어 진행해 develop 브랜치에 합쳐질 예정입니다.

### 개선 방향
1. 평점을 찾는 부분이 n+1 문제가 발생하지 않게 in 쿼리로 관련 멤버 List<Preference>를 가져오게 수정한다.
2. 가져온 List<Preference> 를 다시 sorting이 된 drink 와 연결해 dto를 변환 후 리턴한다.
3. (희망 사항) 각각의 도메인을 직접 참조보다 id 참조 형식으로 변경한다.

### 희망 사항
- 도메인과 서비스가 경계가 불분명하게 서로 많은 관계를 맺고 있습니다. 이에 따라 서로 연관되어 있는 엔티티가 값이 채워져있는지 프록시로 채워져있는지 파악하기가 힘든 문제가 발생합니다. 도메인간의 명확한 경계를 세울 필요가 느껴집니다. 또한, 직접적인 엔티티 참조보다 id 를 바라봄으로 위와 같은 문제를 해결하고 싶습니다. 최종적으로 멀티모듈을 도입함으로 각 도메인간, 레이어간 명확한 경계를 세우고 싶습니다!
[참고 영상 : 조영호 님의 객체지향 영상](https://www.youtube.com/watch?v=dJ5C4qRqAgA)
