### ISSUE TITLE
[Bug] Drinks 선호도 없을 때 에러로 취급되는 이슈

### ISSUE THREAD

**Issue by sunhpark42** [woowacourse-teams/2021-jujeol-jujeol#79]
### 설명
drinks preference 없을 시 에러로 처리 되는 걸, 기본 값 0으로 응답되도록 수정 필요

**Comment by perenok** [comment]
preference 없을 때 에러 대신 기본 0값으로 응답되도록 변경
rate로 요청 보내는 대신 preferenceRate로 변경
사용하지 않는 NoSuchPreferenceException 삭제
feature/detail에 우선 적용했습니다!
실패에 대한 문서도 곧 추가하겠습니다!
