### ISSUE TITLE
[FE] netlify를 이용한 배포 시 github submodule을 찾지 못하는 문제

### ISSUE THREAD

**Issue by sunhpark42** [woowacourse-teams/2021-jujeol-jujeol#84]
### 설명
netlify를 이용한 배포 시 github submodule을 찾지 못하는 이슈

### 진행상황(시도중)
- [x] github submodule 에 netlify ssh등록

**Comment by devhyun637** [comment]
생각하지도 못했던 문제인데.. 먼저 찾아 해결해주셔서 감사합니다 🙏
